name: hello_world_template
description: A simple command-line package that allows you to run a helloWorld function call or sayIt method
version: 1.0.0
repository: "https://github.com/BryceTuppurainen/dart_hello_world"

environment:
  sdk: ">=2.18.3 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
